##
## Makefile for Makefile in /home/uberti_l/rendu/Piscine_C_J12/grep
##
## Made by louis-emile uberti-ares
## Login   <uberti_l@epitech.net>
##
## Started on  Tue Oct 13 09:06:51 2015 louis-emile uberti-ares
## Last update Tue Oct 13 16:19:53 2015 louis-emile uberti-ares
##

NAME	= grep

CC	= cc -o

LIB	= lmy -L../lib/my

OBJ	= grep.c

RM	= rm -rf

all:
	$(CC) $(NAME) $(OBJ) $(LIB)

fclean: clean

clean:
	$(RM) $(NAME)

re: clean
