##
## Makefile for Makefile in /home/uberti_l/rendu/Piscine_C_J12/cat
##
## Made by louis-emile uberti-ares
## Login   <uberti_l@epitech.net>
##
## Started on  Tue Oct 13 09:05:39 2015 louis-emile uberti-ares
## Last update Tue Oct 13 16:19:01 2015 louis-emile uberti-ares
##

NAME	= cat

CC	= cc -o

OBJ	= cat.c

RM	= rm -rf

LIB	= -lmy -L../lib/my/

all:
	@$(CC) $(NAME) $(OBJ) $(LIB)

fclean: clean

clean:
	$(RM) $(NAME)

re: clean all
